package-lock.json, server/db/models/order.js
=> Define order module

server/db/models/index.js, server/db/models/user.js
=> BE: Completes User model, Adds model associations

server/db/models/address.js
=> BE: Creates db address model

server/db/models/product.js
=> feat(product-model) add product model to ./db/model

server/db/models/index.js
=> BE: Imports sequelize

server/db/models/index.js
=> BE: Fixes typos

server/db/models/address.js
=> BE: Changes zip-code data type

server/db/models/product.js
=> BE: Changes price data type

client/components/AllProducts.js, client/components/index.js, client/components/navbar.js, client/routes.js, client/store/allProducts.js, client/store/index.js, script/seed.js, server/db/models/order.js
=> Allproduct

public/index.html, server/api/allProducts.js
=> Be allproducts

client/components/user-home.js
=> feat(home) change home component for quality

server/db/models/address.js, server/db/models/product.js, server/db/models/user.js
edits Address, Product, and User models to have more validations
=> BE: Adds model validations on Address, Product, User

script/seed.js, server/db/models/address.js, server/db/models/product.js, server/db/models/user.js
-removes commented out code
-moves db.sync to runseed func
-successfully seeds thru table to make user-address associations for ten users
-adds login info for our group to enable test login
=> Seed file updates

client/components/AllProducts.js, client/components/user-home.js
=> Home quickfix

client/components/SingleProduct.js, client/store/singleProduct.js, server/api/cart.js, server/api/index.js
=> Cart add product

client/components/AllProducts.js, client/components/SingleProduct.js, client/routes.js, client/store/index.js, client/store/singleProduct.js, server/api/allProducts.js
=> Single product view

client/components/AllProducts.js, client/components/Signup.js, client/components/index.js, client/components/navbar.js, package-lock.json, package.json, public/style.css
=> Usersignup

client/components/AllProducts.js, package-lock.json, package.json, public/style.css
=> FE: page working

client/components/user-home.js, client/routes.js
=> feat(home) change welcome h3 to be dynamic add redirect route to home

script/seed.js, server/api/cart.js
=> order-product through table

adminSecurityNotes.js
=> Admin security notes

client/components/user-home.js, client/store/cart.js
=> feat(home) change home component to create cart for the user

client/components/Signup.js, client/store/user.js
=> FE: userSignUp component

client/components/AddToCart.js, client/components/SingleProduct.js, client/store/cart.js
=> feat(cart) add be order connection to fe AddToCart component

server/db/models/index.js
=> BE: Cleans up db associations

client/components/Cart.js
=> Cart component

client/components/UserList.js
=> FE: Renders UserList successfully

client/components/AddToCart.js, client/components/navbar.js, client/store/cart.js
=> feat(addtocart) debug AddToCart component, thunk and route

client/store/user.spec.js
=> specs for signin and sign up

client/components/AddToCart.js, client/components/user-home.js, client/store/cart.js, server/api/cart.js
=> Addtocart debugged

client/components/Cart.js, client/components/SingleProduct.js, client/components/navbar.js, public/index.html, script/seed.js
=> Product image

client/components/Cart.js, client/components/SubmitOrder.js, client/store/cart.js
=> Submit order

client/components/LocalCart.js, client/components/UserList.spec.js, client/store/index.js, client/store/localCart.js, client/store/localStorage.js, script/seed.js
=> Seed admin

client/components/OrderConfirmation.js, client/components/SubmitOrder.js, client/components/navbar.js, client/index.js, client/store/cart.js, package-lock.json, package.json
=> Order confirmation

client/store/cart.js, server/api/cart.js
=> Restful api

server/api/cart.js
Updates the api PUT route for 'submit order' to iterate through products and update their inventory. Does not account for an item being OOS yet.
=> BE: Updates PUT route to decrease inventory

client/components/Views/Cart.js
=> FE: Cart conditionally renders local/user cart

tests/UserList.spec.js
=> small edit on a test spec

client/components/Views/Cart.js, client/components/Views/LocalCart.js
=> Cart render fix
